apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    cloudfunctions.googleapis.com/function-id: sendEmailCode
    run.googleapis.com/build-base-image: us-central1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs22
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-environment-variables: '{"GOOGLE_NODE_RUN_SCRIPTS":""}'
    run.googleapis.com/build-function-target: sendEmailCode
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/music-academy-75552/gcf-artifacts/music--academy--75552__us--central1__send_email_code:version_1
    run.googleapis.com/build-name: projects/804878148754/locations/us-central1/builds/668259f8-7640-4371-b240-0350f7090c05
    run.googleapis.com/build-service-account: projects/music-academy-75552/serviceAccounts/804878148754-compute@developer.gserviceaccount.com
    run.googleapis.com/build-source-location: gs://gcf-v2-sources-804878148754-us-central1/sendEmailCode/function-source.zip#1738256009222470
    run.googleapis.com/client-name: cli-firebase
    run.googleapis.com/custom-audiences: '["https://us-central1-music-academy-75552.cloudfunctions.net/sendEmailCode"]'
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: e2b2ee26-0c3d-447d-9b4f-4a657d642aff
    run.googleapis.com/urls: '["https://sendemailcode-804878148754.us-central1.run.app","https://us-central1-music-academy-75552.cloudfunctions.net/sendEmailCode","https://sendemailcode-xjqcjc5s3a-uc.a.run.app"]'
    serving.knative.dev/creator: service-804878148754@gcf-admin-robot.iam.gserviceaccount.com
    serving.knative.dev/lastModifier: service-804878148754@gcf-admin-robot.iam.gserviceaccount.com
  creationTimestamp: '2025-01-30T08:18:32.941118Z'
  generation: 8
  labels:
    cloud.googleapis.com/location: us-central1
    goog-cloudfunctions-runtime: nodejs22
    goog-drz-cloudfunctions-id: sendemailcode
    goog-drz-cloudfunctions-location: us-central1
    goog-managed-by: cloudfunctions
  name: sendemailcode
  namespace: '804878148754'
  resourceVersion: AAYs70ZPrfA
  selfLink: /apis/serving.knative.dev/v1/namespaces/804878148754/services/sendemailcode
  uid: aef03cfe-2f31-4bf1-8892-f86bb7fdcd0a
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        cloudfunctions.googleapis.com/trigger-type: HTTP_TRIGGER
        run.googleapis.com/base-images: '{"worker":"us-central1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs22"}'
        run.googleapis.com/client-name: cli-firebase
        run.googleapis.com/secrets: secret-ade0ba7a-1f79-3628-b83c-6526e82dbe93:projects/music-academy-75552/secrets/EMAIL_USER,secret-fffb998b-bab0-3c9e-8173-3700cd67046f:projects/music-academy-75552/secrets/EMAIL_PASS
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
      name: sendemailcode-00008-xez
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: FIREBASE_CONFIG
          value: '{"projectId":"music-academy-75552","storageBucket":"music-academy-75552.firebasestorage.app"}'
        - name: GCLOUD_PROJECT
          value: music-academy-75552
        - name: EVENTARC_CLOUD_EVENT_SOURCE
          value: projects/music-academy-75552/locations/us-central1/services/sendEmailCode
        - name: FUNCTION_TARGET
          value: sendEmailCode
        - name: LOG_EXECUTION_ID
          value: 'true'
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              key: '2'
              name: secret-ade0ba7a-1f79-3628-b83c-6526e82dbe93
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              key: '2'
              name: secret-fffb998b-bab0-3c9e-8173-3700cd67046f
        image: us-central1-docker.pkg.dev/music-academy-75552/gcf-artifacts/music--academy--75552__us--central1__send_email_code:version_1
        name: worker
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 256Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: 804878148754-compute@developer.gserviceaccount.com
      timeoutSeconds: 30
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://sendemailcode-xjqcjc5s3a-uc.a.run.app
  conditions:
  - lastTransitionTime: '2025-01-30T16:54:08.696816Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2025-01-30T16:54:07.430820Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-01-30T16:54:08.656485Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: sendemailcode-00008-xez
  latestReadyRevisionName: sendemailcode-00008-xez
  observedGeneration: 8
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: sendemailcode-00008-xez
  url: https://sendemailcode-xjqcjc5s3a-uc.a.run.app
